In [22]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures as PF
from sklearn.linear_model import LinearRegression as LR

# import data
test_data=pd.read_csv("data.csv")
x=test_data.iloc[:,0].values.reshape(-1,1)
y=test_data.iloc[:,1].values

# set polynomial features

x_poly=PF().fit_transform(x)

# Conduct Linear Regression
model=LR().fit(x_poly, y)


In [19]:
X

array([[-0.33532],
       [ 0.0216 ],
       [-1.19438],
       [-0.65046],
       [-0.28001],
       [ 1.93258],
       [ 1.2262 ],
       [ 0.74727],
       [ 3.32853],
       [ 2.87457],
       [-1.48662],
       [ 0.37629],
       [ 1.43918],
       [ 0.24183],
       [-2.7914 ],
       [ 1.08176],
       [ 2.81555],
       [ 0.54924],
       [ 2.36449],
       [-1.01925]])

In [25]:
import pandas as pd
from sklearn.linear_model import Lasso, LinearRegression as LR


# Assign the data to predictor and outcome variables
# TODO: Load the data
train_data = pd.read_csv('data2.csv',header=None)
X = train_data.iloc[:,:-1].values
y = train_data.iloc[:,-1].values

# TODO: Create the linear regression model with lasso regularization.
lasso_reg = Lasso()


# TODO: Fit the model.
lasso_reg.fit(X,y)

# TODO: Retrieve and print out the coefficients from the regression model.
reg_coef = lasso_reg.coef_
print(reg_coef)



# Note that the first feature was zeroed out and is no longer applicable

[ 0.          2.35793224  2.00441646 -0.05511954 -3.92808318  0.        ]


In [26]:
model=LR().fit(X,y)

In [27]:
model.coef_

array([ -6.19918532e-03,   2.96325160e+00,   1.98199191e+00,
        -7.86249920e-02,  -3.95818772e+00,   9.30786141e+00])

feature scaling - transform your data to common range

    standardization - take each value and subtract mean then divide by std deviation
    normalization - data is scaled between 0 and 1
        df[heightnorm]=(df[height]-df[height].min())/ (df[height].max() - df['height'].min())
        
when to use?
    when algorithm uses distance based metric to predict
    when you incorporate regularization
techniques used 
    k nearest neighbors
    svm

    

In [12]:
import pandas as pd
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.preprocessing import StandardScaler

# import data
test_data=pd.read_csv('data.csv',header=None)
X=test_data.iloc[:,:-1]
y=test_data.iloc[:,-1]

# Feature scale it using Standardization( distance from mean divided by std dev
# do this to ensure all features are treated equally
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

# regularize in order to help with feature selection and reduc error

lasso_reg=Lasso().fit(X_scaled,y)

reg_coef=lasso_reg.coef_

ValueError: could not convert string to float: 'Var_X'

In [8]:
reg_coef

array([-3.24778313])